apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-core
  labels:
    app: rasa
    component: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa
      component: core
  template:
    metadata:
      labels:
        app: rasa
        component: core
    spec:
      initContainers:
        - name: download-models
          image: alpine/git:latest
          command:
            - sh
            - -c
            - |
              echo "Клонируем репозиторий..."
              git clone https://github.com/elbukaevzaur/ai-chat-bot.git /model-repo &&
              cp -r /model-repo/models/* /app/models/ &&
              ls /app/models/ &&
              echo "Модели успешно загружены."
          volumeMounts:
            - name: rasa-models
              mountPath: /app/models
      containers:
        - name: rasa-core
          image: rasa/rasa:3.0.0
          ports:
            - containerPort: 5005
          env:
            - name: RASA_PORT
              value: "5005"
          command:
            - sh
            - -c
            - |
              echo "Обучаем модель..."
              rasa train --data /app/models/data --domain /app/models/domain.yml --config /app/models/config.yml --out /app/models &&
              echo "Модель успешно обучена, запускаем Rasa Core..."
              rasa run --model /app/models/model.tar.gz --port $RASA_PORT
          volumeMounts:
            - name: rasa-models
              mountPath: /app/models
      volumes:
        - name: rasa-models
          emptyDir: {}
---
# Ingress для внешнего доступа к Rasa Core
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rasa-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rasa-core
                port:
                  number: 5005